name: Tests
on: push

jobs:
  tests:
    strategy:
      matrix:
        python-version: ['3.9']
    name: Python ${{ matrix.python-version }}
    uses: Informasjonsforvaltning/workflows/.github/workflows/test-nox.yaml@main
    with:
      python-version: ${{ matrix.python-version }}
      architecture: x64
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
